import { expect, test } from '@playwright/test';
import sharp from 'sharp';

test('M4 menu journey persists bilingual content, images and conflict recovery on desktop and mobile', async ({ page, request, browser }) => {
  test.setTimeout(90_000);
  await page.context().setExtraHTTPHeaders({ 'x-daify-test-client-ip': '192.0.2.80' });
  const email = `menus-${Date.now()}@example.com`;
  const password = 'correct horse battery staple';
  const signup = await request.post('http://127.0.0.1:4000/api/v1/auth/signup', { headers: { Origin: 'http://127.0.0.1:3100' }, data: { email, displayName: 'Menu Reviewer', password } });
  expect(signup.ok()).toBeTruthy();
  const { verificationToken } = await signup.json() as { verificationToken: string };
  await page.goto(`/verify-email?token=${encodeURIComponent(verificationToken)}`);
  await expect(page.getByRole('heading', { name: 'Email verified.' })).toBeVisible();
  await page.goto('/login');
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: /Log in/ }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await page.getByLabel('Restaurant or group name').fill('M4 Test Kitchen');
  await page.getByLabel('Short name', { exact: true }).fill(`m4-${Date.now()}`);
  await page.getByRole('button', { name: 'Create workspace' }).click();
  await page.getByLabel('Location name').fill('Kuwait City');
  await page.getByLabel('Short name', { exact: true }).fill('kuwait-city');
  await page.getByRole('button', { name: 'Add location' }).click();
  await expect(page.getByText('Kuwait City', { exact: true })).toBeVisible();
  await page.goto('/dashboard/menus');
  await page.getByRole('button', { name: 'Create menu', exact: true }).click();
  const create = page.getByRole('form', { name: 'Create menu', exact: true });
  await create.getByLabel('Menu name').fill('Dinner');
  await create.getByLabel('Short name').fill('dinner');
  await create.getByLabel('Languages').selectOption('en,ar');
  await create.getByRole('button', { name: 'Create draft' }).click();
  await expect(page.getByRole('heading', { name: 'Dinner', exact: true })).toBeVisible();
  await page.getByText('Menu settings and translations', { exact: true }).click();
  const settings = page.getByRole('form', { name: 'Menu settings', exact: true });
  await settings.getByLabel('Name (ar)', { exact: true }).fill('قائمة العشاء');
  await settings.getByRole('button', { name: 'Save menu settings' }).click();
  await expect(page.getByRole('status')).toHaveText('Changes saved.');
  const section = page.getByRole('form', { name: 'Add section', exact: true });
  await section.getByLabel('Name (en)', { exact: true }).fill('Starters');
  await section.getByLabel('Name (ar)', { exact: true }).fill('المقبلات');
  await section.getByRole('button', { name: 'Add section', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Starters', exact: true })).toBeVisible();
  await page.getByText('Add an item', { exact: true }).click();
  const addItem = page.getByRole('form', { name: 'Add item to Starters', exact: true });
  await addItem.getByLabel('Name (en)', { exact: true }).fill('Lentil soup');
  await addItem.getByLabel('Name (ar)', { exact: true }).fill('شوربة العدس');
  await expect(addItem.getByLabel('Name (ar)', { exact: true })).toHaveAttribute('dir', 'rtl');
  await addItem.getByLabel('Price (KWD)').fill('2.750');
  await addItem.getByLabel('Dietary tags (comma separated)').fill('vegetarian');
  await addItem.getByLabel('Featured', { exact: true }).check();
  await addItem.getByRole('button', { name: 'Add item', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Lentil soup', exact: true })).toBeVisible();
  await page.getByText('Edit item', { exact: true }).click();
  const upload = page.getByRole('form', { name: 'Upload image for Lentil soup', exact: true });
  const buffer = await sharp({ create: { width: 480, height: 320, channels: 3, background: '#df9c43' } }).png().toBuffer();
  await upload.locator('input[type=file]').setInputFiles({ name: 'soup.png', mimeType: 'image/png', buffer });
  await upload.getByLabel('New image description (en)', { exact: true }).fill('Golden soup');
  await upload.getByLabel('New image description (ar)', { exact: true }).fill('شوربة ذهبية');
  await upload.getByRole('button', { name: 'Upload image', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Image saved.');
  const image = page.getByRole('img', { name: 'Golden soup', exact: true });
  await expect(image).toBeVisible();
  await expect.poll(() => image.evaluate(node => (node as HTMLImageElement).naturalWidth)).toBe(480);
  const imagePath = await image.getAttribute('src');
  const menuPath = imagePath!.split('/images/')[0]!;
  expect((await request.get(imagePath!)).status()).toBe(401);
  expect((await page.request.patch(menuPath, { headers: { Origin: 'http://127.0.0.1:3100' }, data: { padding: 'x'.repeat(101 * 1024) } })).status()).toBe(413);
  expect((await page.request.get(`${menuPath}/unsupported`)).status()).toBe(404);
  const currentResponse = await page.request.get(menuPath);
  expect(currentResponse.ok()).toBeTruthy();
  const current = await currentResponse.json() as { draftRevision: number };
  const otherSession = await page.request.patch(menuPath, { headers: { Origin: 'http://127.0.0.1:3100' }, data: { revision: current.draftRevision, name: 'Dinner updated elsewhere' } });
  expect(otherSession.ok()).toBeTruthy();
  await page.getByText('Edit item', { exact: true }).click();
  const editItem = page.getByRole('form', { name: 'Edit item Lentil soup', exact: true });
  await editItem.getByLabel('Price (KWD)').fill('3.000');
  await editItem.getByRole('button', { name: 'Save item', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'another session' })).toBeVisible();
  await expect(editItem.getByLabel('Price (KWD)')).toHaveValue('3.000');
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Reload latest draft' }).click();
  await expect(page.getByRole('heading', { name: 'Dinner updated elsewhere' })).toBeVisible();
  await page.getByText('Edit item', { exact: true }).click();
  await expect(editItem.getByLabel('Price (KWD)')).toHaveValue('2.750');
  await editItem.getByLabel('Price (KWD)').fill('3.000');
  await editItem.getByRole('button', { name: 'Save item', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Changes saved.');
  await page.getByRole('button', { name: 'Mark unavailable', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Mark available', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'All menus', exact: true }).click();
  await page.reload();
  await page.getByRole('button', { name: 'Open Dinner updated elsewhere', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Mark available', exact: true })).toBeVisible();
  await expect(page.getByLabel('Translation completeness')).toContainText('Required names complete');
  const noJs = await browser.newContext({ javaScriptEnabled: false, storageState: await page.context().storageState(), extraHTTPHeaders: { 'x-daify-test-client-ip': '192.0.2.80' } });
  try {
    const readonly = await noJs.newPage();
    await readonly.goto('http://127.0.0.1:3100/dashboard/menus', { waitUntil: 'domcontentloaded' });
    // The streaming shell can omit the editor without JavaScript.
    await expect(readonly).toHaveURL(/\/dashboard\/menus$/);
    await expect(readonly.locator('main fieldset button:enabled')).toHaveCount(0);
    await expect(readonly.locator('main form input:enabled')).toHaveCount(0);
  } finally { await noJs.close(); }
  await page.setViewportSize({ width: 1440, height: 1000 });
  if (process.env.QA_EVIDENCE_DIR) await page.screenshot({ path: `${process.env.QA_EVIDENCE_DIR}/menus-desktop.png`, fullPage: true });
  await page.getByLabel('View language').selectOption('ar');
  await expect(page.getByRole('heading', { name: 'شوربة العدس', exact: true })).toHaveAttribute('dir', 'rtl');
  await expect(page.getByRole('img', { name: 'شوربة ذهبية', exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator('#dashboard-sidebar')).toHaveAttribute('inert', '');
  await expect.poll(() => page.locator('#dashboard-sidebar').evaluate(node => node.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  if (process.env.QA_EVIDENCE_DIR) await page.screenshot({ path: `${process.env.QA_EVIDENCE_DIR}/menus-mobile-ar.png`, animations: 'disabled', fullPage: true });
  await page.getByText('Edit item', { exact: true }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Archive item', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'شوربة العدس', exact: true })).toHaveCount(0);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Archive menu', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Menu archived.');
  await page.goto('/dashboard/restaurant');
  const locationForm = page.getByRole('form', { name: 'Edit Kuwait City', exact: true });
  await locationForm.getByLabel('Location name', { exact: true }).fill('Kuwait City Updated');
  await locationForm.getByRole('button', { name: 'Save location', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Kuwait City Updated', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Kuwait City Updated', exact: true })).toBeVisible();
});
